### PR TITLE
Added boilerplate config

### PR DESCRIPTION
**Pull request by evalsocket**
- Added for the experiment. 
Why : Currently if we add something new in boilerplate then we have to make a manual update in `update.cfg` that's boring. Can we create a centralized config for adding files from the boilerplate?

### CODE REVIEW

**Comment by evalsocket** [comment]
CC: @EngHabu

**Comment by EngHabu** [comment]
I like the more decenteralized approach where each repo imports what they need...

**Comment by evalsocket** [comment]
We only copy those files that are needed by a repo.  The difference is now we have that config in one place. No need to create PR in each repo for adding consistent change. 

Like I added pre-commit dir that will be used by every repo. Now after the boilerplate change, I need to add config in each repo manually but if we have config at boilerplate level then we can update it with our change

**Comment by kumare3** [comment]
One comment over here and @EngHabu and @evalsocket yoi guys are better judges, but I think boilerplate itself has become good enough to be a standalone offering. If so should we keep it open?

Or is it very custom and folks who want to do similar stuff will need to clone and edit. If so I love this

**Pull request closed without merging**
